### PR TITLE
upgrade to 6.1.3 and fix windows compilation

### LINKED ISSUE #14: windows not installing static lib
Files in the current Windows package:

- Library\include\shogun\*
- Library\share\shogun\examples\libshogun\minimal.exe
- Library\lib\shogun.lib

@vigsterkr, should it be installing the static library too?

### PR DESCRIPTION
**Pull request by vigsterkr**
Fixes #14.

### CODE REVIEW

**Comment by vigsterkr** [comment]
@dougalsutherland ok so as you can see the windows has been successfully built \o/ let's hope the travis is going to build nicely as well... then we can merge this :)

**Comment by djsutherland** [comment]
@vigsterkr Building locally rather than waiting for Travis because this is exciting to merge; will let you know if it builds. :)

Should I just release 6.2.0 though instead of bothering with 6.1.3 – no real changes so hopefully no need to retest?

**Comment by vigsterkr** [comment]
@dougalsutherland 6.2.0 is just the next version in preparation - dont get fooled by develop :)
let's release 6.1.3 both the shogun-cpp and shogun packages as well, with windows :)

**Comment by djsutherland** [comment]
Hah okay.

Mac built locally, so merging! Python interface next. :)

**Comment by vigsterkr** [comment]
\o/

**Pull request merged**
