### PR TITLE
try new windows build script variation

### LINKED ISSUE #14: windows not installing static lib
Files in the current Windows package:

- Library\include\shogun\*
- Library\share\shogun\examples\libshogun\minimal.exe
- Library\lib\shogun.lib

@vigsterkr, should it be installing the static library too?

### PR DESCRIPTION
**Pull request by djsutherland**
Attempt to fix #14.

### CODE REVIEW

**Comment by djsutherland** [comment]
@vigsterkr What should the static library be named, btw? I'll add a test for it but not sure what path it should be. :)

(This time got `%1 is not a valid Win32 application`, so possibly it actually built x86. Explicitly adding the platform x64 now.)

**Comment by vigsterkr** [comment]
yeah this is expected to fail
```
(C:\bld\shogun-cpp_1511977014324\_t_env) (root) C:\bld\shogun-cpp_1511977014324\test_tmp>python -c "import os, ctypes; ctypes.cdll[os.path.join(os.environ['LIBRARY_LIB'], 'shogun.lib')]" 
```

it should be:
```
python -c "import os, ctypes; ctypes.cdll[os.path.join(os.environ['LIBRARY_LIB'], 'shogun.dll')]"
```

only thing is that i dont see `shogun.dll` installed :(

**Comment by djsutherland** [comment]
Yeah, this version is still only installing `lib/shogun.lib`. Something up with the cmake definitions, I guess....

**Comment by vigsterkr** [comment]
i reckon this should be closed in favour of #18

**Pull request closed without merging**
