### PR TITLE
switch to libprotobuf

### PR DESCRIPTION
**Pull request by djsutherland**

### CODE REVIEW

**Comment by djsutherland** [comment]
Hmm:
```
[100%] Linking CXX executable minimal
../../src/shogun/libshogun.so.18.0: undefined reference to `google::protobuf::Message::InitializationErrorString() const'
../../src/shogun/libshogun.so.18.0: undefined reference to `google::protobuf::Message::GetTypeName() const'
../../src/shogun/libshogun.so.18.0: undefined reference to `google::protobuf::internal::AssignDescriptors(std::string const&, google::protobuf::internal::MigrationSchema const*, google::protobuf::Message const* const*, unsigned int const*, google::protobuf::MessageFactory*, google::protobuf::Metadata*, google::protobuf::EnumDescriptor const**, google::protobuf::ServiceDescriptor const**)'
../../src/shogun/libshogun.so.18.0: undefined reference to `google::protobuf::MessageFactory::InternalRegisterGeneratedFile(char const*, void (*)(std::string const&))'
collect2: error: ld returned 1 exit status
```

Also, it was actually pulled in from `defaults`, because we only have `3.5` in conda-forge even though conda-forge-pinning has it at 3.4....

**Comment by djsutherland** [comment]
Not worth debugging until conda-forge switches to `libprotobuf 3.5` (https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/14), since all this gains over the current build is (hopefully) protobuf support on Windows.

**Comment by jakirkham** [comment]
So the `protobuf` on conda-forge had both C++ and Python included since PR ( https://github.com/conda-forge/protobuf-feedstock/pull/4 ). The addition of `libprotobuf` merely broke out the C++ part.

**Comment by djsutherland** [comment]
At least at some point, I think it only had the C API and not the C++ API on Windows (because the Python C++ interaction was broken or something). Not finding where that was happening in a quick search and doesn't really matter, though. :)

**Comment by djsutherland** [comment]
Depends on https://github.com/conda-forge/libprotobuf-feedstock/pull/2.

**Comment by djsutherland** [comment]
Was already done in #20, but making Windows protobuf support #22.

**Pull request closed without merging**
