### PR TITLE
update to 6.1.4; new blas scheme

### PR DESCRIPTION
**Pull request by djsutherland**
Updated to shogun 6.1.4 (only changed the examples, I think) and more importantly changed to the current BLAS scheme.

- Closes #29 (update version)
- Closes #26 (blas scheme)
- Closes #25, closes #28, closes #31 (protobuf version updates)
- Closes #27 (hdf5 update)

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by djsutherland** [comment]
Windows is saying `jom: parallel job execution disabled for Makefile`. Not sure what that's about. More importantly, there's a lot of static / dynamic linking errors:

```
shogun.lib(StreamingDataFetcher.cpp.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in minimal.cpp.obj
```

Need to try fiddling with that I suppose....

**Comment by xhochy** [comment]
@dougalsutherland you might give ninja a try on windows as done in e.g.: https://github.com/conda-forge/openjpeg-feedstock/pull/37/commits/0a9e1923fc7273080af2f372f412ab4faea7680f

**Comment by djsutherland** [comment]
@xhochy Yeah, I tried that earlier but got

```
ninja: error: build.ninja:5842: multiple rules generate src/shogun/shogun.lib [-w dupbuild=err]
```

Also, for the record, `jom` is giving me (at the end) lots of
```
shogun.lib(DenseMatrixOperator.cpp.obj) : error LNK2038: mismatch detected for 
'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in 
minimal.cpp.obj
```
which I have no idea how to address. Running a non-parallel build now to see if it's the same with plain `nmake` or not.

Not sure why this built fine on AppVeyor before but hard timed-out well before finishing this time; maybe their machines got slower.

**Comment by djsutherland** [comment]
Okay, regular `nmake` gives the same problem as `jom`, so at least it's not that.

@vigsterkr – any idea here? Basically:

- I'm trying to update our shogun builds to the current conda-forge setup. Right now they only work with older software, but the upgrade will more importantly build against netlib BLAS and then let users link against whatever BLAS they want (MKL, OpenBLAS, ...).

- AppVeyor is now timing out for the shogun builds (maybe it got slower).

- conda-forge has mostly switched to Azure, where CMake doesn't work with MSBuild (https://github.com/conda-forge/conda-forge.github.io/issues/703).

- Ninja refuses to generate (`multiple rules generate src/shogun/shogun.lib`).

- NMake, or `jom`, build but then at the end give lots of errors like
  ```
  shogun.lib(DenseMatrixOperator.cpp.obj) : error LNK2038: mismatch detected for 
  'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in 
  minimal.cpp.obj
  ```
  Do you know how to approach this?

**Comment by vigsterkr** [comment]
should be closed in favour of https://github.com/conda-forge/shogun-cpp-feedstock/pull/34

**Pull request closed without merging**
